version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    command: gunicorn pilgrims.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - DEBUG=0
