# Generated by Django 5.2 on 2025-10-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerycategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='name_lo',
            field=models.CharField(blank=True, help_text='Name in Lao', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(help_text='Name in English', max_length=100, unique=True),
        ),
    ]
