# Generated by Django 5.2 on 2025-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerycategory_name_lo_alter_gallerycategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='description_lo',
            field=models.TextField(blank=True, help_text='Description in Lao'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_lo',
            field=models.CharField(blank=True, help_text='Title in Lao', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, help_text='Description in English'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, help_text='Title in English', max_length=200),
        ),
    ]
