# Generated by Django 5.2 on 2025-06-06 15:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReviewPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("agoda", "Agoda"),
                            ("booking", "Booking.com"),
                            ("airbnb", "Airbnb"),
                            ("tripadvisor", "TripAdvisor"),
                            ("google", "Google Reviews"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "brand_color",
                    models.CharField(
                        default="#000000", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Review Platform",
                "verbose_name_plural": "Review Platforms",
                "ordering": ["display_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "featured_stat_1_label",
                    models.CharField(default="Excellence Rating", max_length=100),
                ),
                (
                    "featured_stat_1_value",
                    models.CharField(default="4.8/5", max_length=50),
                ),
                (
                    "featured_stat_2_label",
                    models.CharField(default="Guest Satisfaction", max_length=100),
                ),
                (
                    "featured_stat_2_value",
                    models.CharField(default="98%", max_length=50),
                ),
                (
                    "featured_stat_3_label",
                    models.CharField(default="Repeat Guests", max_length=100),
                ),
                (
                    "featured_stat_3_value",
                    models.CharField(default="85%", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Review Summary",
                "verbose_name_plural": "Review Summary",
            },
        ),
        migrations.CreateModel(
            name="ReviewCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="home.reviewplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Category",
                "verbose_name_plural": "Review Categories",
                "ordering": ["platform", "display_order", "name"],
                "unique_together": {("name", "platform")},
            },
        ),
        migrations.CreateModel(
            name="PlatformRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="home.reviewplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Rating",
                "verbose_name_plural": "Platform Ratings",
            },
        ),
        migrations.CreateModel(
            name="GuestReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                ("review_text", models.TextField()),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("family", "Family Vacation"),
                            ("business", "Business Trip"),
                            ("solo", "Solo Traveler"),
                            ("couple", "Couple's Trip"),
                            ("friends", "Friends Trip"),
                            ("weekend", "Weekend Getaway"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=True)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("is_superhost_review", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="home.reviewplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Review",
                "verbose_name_plural": "Guest Reviews",
                "ordering": ["-review_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategoryRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.reviewcategory",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_ratings",
                        to="home.reviewplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Rating",
                "verbose_name_plural": "Category Ratings",
                "unique_together": {("platform", "category")},
            },
        ),
    ]
