# Generated by Django 5.2 on 2025-06-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categoryrating",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="categoryrating",
            name="category",
        ),
        migrations.RemoveField(
            model_name="categoryrating",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="guestreview",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="platformrating",
            name="platform",
        ),
        migrations.AlterUniqueTogether(
            name="reviewcategory",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="reviewcategory",
            name="platform",
        ),
        migrations.DeleteModel(
            name="ReviewSummary",
        ),
        migrations.DeleteModel(
            name="CategoryRating",
        ),
        migrations.DeleteModel(
            name="GuestReview",
        ),
        migrations.DeleteModel(
            name="PlatformRating",
        ),
        migrations.DeleteModel(
            name="ReviewCategory",
        ),
        migrations.DeleteModel(
            name="ReviewPlatform",
        ),
    ]
