# Generated by Django 5.2 on 2025-05-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("coffee", "Coffee"),
                    ("american", "American"),
                    ("indian", "Indian"),
                    ("drinks", "Drinks"),
                    ("mexican", "Mexican"),
                    ("pizza", "Pizza"),
                    ("local_food", "Local Food"),
                    ("soup_salad_mediterranean", "Soup & Salad Mediterranean"),
                ],
                max_length=50,
            ),
        ),
    ]
