# Generated by Django 5.2 on 2025-10-15 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_populate_menucategory_and_copy_data'),
    ]

    operations = [


    ]
