# Generated by Django 5.2 on 2025-05-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_menuitem_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="is_gluten_free",
            new_name="is_featured",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="is_vegan",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="is_vegetarian",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("coffee", "Coffee"),
                    ("american", "American"),
                    ("indian", "Indian"),
                    ("drinks", "Drinks"),
                    ("mexican", "Mexican"),
                    ("pizza", "Pizza"),
                    ("local_food", "Local Food"),
                    ("soup_salad_mediterranean", "Soup, Salad & Mediterranean"),
                ],
                max_length=50,
            ),
        ),
    ]
