# Generated by Django 5.2 on 2025-09-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menuitem_category_delete_categorymenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('coffee', 'Coffee'), ('dessert', 'Dessert'), ('american', 'American'), ('indian', 'Indian'), ('drinks', 'Drinks'), ('mexican', 'Mexican'), ('pizza', 'Pizza'), ('local_food', 'Local Food'), ('soup_salad_mediterranean', 'Soup, Salad & Mediterranean')], max_length=50, null=True),
        ),
    ]
