# Generated by Django 5.2 on 2025-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_rename_is_gluten_free_menuitem_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
