# Generated by Django 5.2 on 2025-10-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_menuitem_category_temp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['name'], 'verbose_name': 'Menu Category', 'verbose_name_plural': 'Menu Categories'},
        ),
    ]
