# Generated by Django 5.2 on 2025-07-01 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_roomimage_delete_hotelimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome icon class (e.g., fas fa-wifi)",
                        max_length=50,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("red", "Red"),
                            ("teal", "Teal"),
                            ("pink", "Pink"),
                            ("indigo", "Indigo"),
                            ("yellow", "Yellow"),
                            ("gray", "Gray"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Mark as premium amenity"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "additional_info",
                    models.CharField(
                        blank=True,
                        help_text="Extra details about this amenity for this room",
                        max_length=200,
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.amenity"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Amenity",
                "verbose_name_plural": "Room Amenities",
                "unique_together": {("room", "amenity")},
            },
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms",
                through="hotel.RoomAmenity",
                to="hotel.amenity",
            ),
        ),
    ]
