# Generated by Django 5.2 on 2025-07-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_amenitycategory_amenity_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenity",
            name="category",
        ),
        migrations.DeleteModel(
            name="AmenityCategory",
        ),
    ]
