# Generated by Django 5.2 on 2025-09-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_amenity_category_delete_amenitycategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_type', 'id'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='view_type',
        ),
    ]
