# Generated by Django 5.2 on 2025-09-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_options_remove_room_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in_date',
            field=models.DateTimeField(blank=True, help_text='Current guest check-in date', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out_date',
            field=models.DateTimeField(blank=True, help_text='Current guest check-out date', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='current_guest_email',
            field=models.EmailField(blank=True, help_text='Email of current guest', max_length=254),
        ),
        migrations.AddField(
            model_name='room',
            name='current_guest_name',
            field=models.CharField(blank=True, help_text='Name of current guest', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='is_checked_in',
            field=models.BooleanField(default=False, help_text='Is there a guest currently checked in'),
        ),
    ]
