# Generated by Django 5.2 on 2025-09-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_check_in_date_room_check_out_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_guest_email',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_guest_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_checked_in',
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in_date',
            field=models.CharField(blank=True, default='', help_text='Check-in date as text', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out_date',
            field=models.CharField(blank=True, default='', help_text='Check-out date as text', max_length=20),
        ),
    ]
