# Generated by Django 5.2 on 2025-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_room_current_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
