# Generated by Django 5.2 on 2025-09-25 04:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
        migrations.AlterField(
            model_name='guestreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
        migrations.AlterField(
            model_name='platformrating',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='featured_stat_1_value',
            field=models.CharField(default='9.6/10', max_length=50),
        ),
    ]
