# Generated by Django 5.2 on 2025-09-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_update_rating_scale_to_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewplatform',
            name='name',
            field=models.CharField(choices=[('agoda', 'Agoda'), ('booking', 'Booking.com'), ('airbnb', 'Airbnb'), ('tripadvisor', 'TripAdvisor'), ('google', 'Google Reviews'), ('expedia', 'Expedia')], max_length=50, unique=True),
        ),
    ]
