# Generated by Django 5.2 on 2025-09-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_reviewplatform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestreview',
            name='trip_type',
            field=models.CharField(choices=[('family', 'Family Vacation'), ('business', 'Business Trip'), ('solo', 'Solo Traveler'), ('couple', "Couple's Trip"), ('friends', 'Friends Trip'), ('weekend', 'Weekend Getaway'), ('traveled_with_partner', 'Traveled with partner'), ('other', 'Other')], default='other', max_length=25),
        ),
    ]
