# Generated by Django 5.2 on 2025-06-03 01:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoffeeBean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ຊື່ເມັດກາເຟ")),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("arabica", "ອາຣາບິກາ"),
                            ("robusta", "ໂຣບັສຕາ"),
                            ("liberica", "ລິເບຣິກາ"),
                            ("excelsa", "ເອັກເຊວຊາ"),
                        ],
                        max_length=20,
                        verbose_name="ປະເພດເມັດ",
                    ),
                ),
                (
                    "country",
                    models.CharField(max_length=50, verbose_name="ປະເທດຕົ້ນກຳເນີດ"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="ພາກພື້ນ"),
                ),
                (
                    "altitude",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ຄວາມສູງ (ແມັດ)"
                    ),
                ),
                (
                    "flavor_notes",
                    models.TextField(blank=True, verbose_name="ລົດຊາດແລະກິ່ນ"),
                ),
                (
                    "acidity_level",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="ລະດັບຄວາມສົ້ມ (1-5)",
                    ),
                ),
                (
                    "body_level",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="ຄວາມເຂັ້ມຂຸ້ນ (1-5)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ເມັດກາເຟ",
                "verbose_name_plural": "ເມັດກາເຟ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CoffeeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="ຊື່ໝວດໝູ່"),
                ),
                ("description", models.TextField(blank=True, verbose_name="ຄຳອະທິບາຍ")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="ຮູບພາບ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ໝວດໝູ່ກາເຟ",
                "verbose_name_plural": "ໝວດໝູ່ກາເຟ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoastLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("light", "ຄັ່ວອ່ອນ"),
                            ("medium_light", "ຄັ່ວອ່ອນກາງ"),
                            ("medium", "ຄັ່ວກາງ"),
                            ("medium_dark", "ຄັ່ວເຂັ້ມກາງ"),
                            ("dark", "ຄັ່ວເຂັ້ມ"),
                            ("french", "ຄັ່ວແບບຝຣັ່ງ"),
                            ("italian", "ຄັ່ວແບບອິຕາລີ"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="ລະດັບການຄັ່ວ",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="ຄຳອະທິບາຍ")),
                (
                    "temperature_range",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ຊ່ວງອຸນຫະພູມ"
                    ),
                ),
            ],
            options={
                "verbose_name": "ລະດັບການຄັ່ວ",
                "verbose_name_plural": "ລະດັບການຄັ່ວ",
            },
        ),
        migrations.CreateModel(
            name="CoffeeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ຊື່ຜະລິດຕະພັນ")),
                (
                    "grind_type",
                    models.CharField(
                        choices=[
                            ("whole_bean", "ເມັດເຕັມ"),
                            ("coarse", "ບົດຫຍາບ"),
                            ("medium_coarse", "ບົດກາງຫຍາບ"),
                            ("medium", "ບົດກາງ"),
                            ("medium_fine", "ບົດກາງລະອຽດ"),
                            ("fine", "ບົດລະອຽດ"),
                            ("extra_fine", "ບົດລະອຽດພິເສດ"),
                        ],
                        default="whole_bean",
                        max_length=20,
                        verbose_name="ປະເພດການບົດ",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="ນ້ຳໜັກ",
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("g", "ກຣາມ"), ("kg", "ກິໂລກຣາມ")],
                        default="g",
                        max_length=5,
                        verbose_name="ໜ່ວຍນ້ຳໜັກ",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="ລາຄາ (ກີບ)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="ຄຳອະທິບາຍ")),
                (
                    "brewing_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ວິທີການຊົງ"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="ຈຳນວນໃນສະຕັອກ"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="ມີຈຳໜ່າຍ"),
                ),
                (
                    "roast_date",
                    models.DateField(blank=True, null=True, verbose_name="ວັນທີຄົ້ວ"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="ວັນທີໝົດອາຍຸ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="coffee.coffeecategory", verbose_name="ໝວດໝູ່"
                    ),
                ),
                (
                    "coffee_bean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.coffeebean",
                        verbose_name="ເມັດກາເຟ",
                    ),
                ),
                (
                    "roast_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.roastlevel",
                        verbose_name="ລະດັບການຄັ່ວ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ຜະລິດຕະພັນກາເຟ",
                "verbose_name_plural": "ຜະລິດຕະພັນກາເຟ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CoffeeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(max_length=100, verbose_name="ຊື່ຜູ້ຣີວິວ"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="ຄະແນນ (1-5 ດາວ)",
                    ),
                ),
                ("comment", models.TextField(verbose_name="ຄຳເຫັນ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="coffee.coffeeproduct",
                        verbose_name="ຜະລິດຕະພັນກາເຟ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ການຣີວິວກາເຟ",
                "verbose_name_plural": "ການຣີວິວກາເຟ",
                "ordering": ["-created_at"],
            },
        ),
    ]
