# Generated by Django 5.2 on 2025-06-03 05:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coffeebean",
            options={},
        ),
        migrations.AlterModelOptions(
            name="coffeecategory",
            options={},
        ),
        migrations.AlterModelOptions(
            name="coffeeproduct",
            options={},
        ),
        migrations.AlterModelOptions(
            name="coffeereview",
            options={},
        ),
        migrations.AlterModelOptions(
            name="roastlevel",
            options={},
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="altitude",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="flavor_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="origin",
            field=models.CharField(
                choices=[
                    ("arabica", "ອາຣາບິກາ"),
                    ("robusta", "ໂຣບັສຕາ"),
                    ("liberica", "ລິເບຣິກາ"),
                    ("excelsa", "ເອັກເຊວຊາ"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coffeebean",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="coffeecategory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="coffeecategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="coffeecategory",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="brewing_method",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="categories",
            field=models.ManyToManyField(blank=True, to="coffee.coffeecategory"),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="coffee_bean",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="coffee.coffeebean"
            ),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="grind_type",
            field=models.CharField(
                choices=[
                    ("whole_bean", "ເມັດເຕັມ"),
                    ("coarse", "ບົດຫຍາບ"),
                    ("medium_coarse", "ບົດກາງຫຍາບ"),
                    ("medium", "ບົດກາງ"),
                    ("medium_fine", "ບົດກາງລະອຽດ"),
                    ("fine", "ບົດລະອຽດ"),
                    ("extra_fine", "ບົດລະອຽດພິເສດ"),
                ],
                default="whole_bean",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="roast_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="roast_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="coffee.roastlevel"
            ),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="coffeeproduct",
            name="weight_unit",
            field=models.CharField(
                choices=[("g", "ກຣາມ"), ("kg", "ກິໂລກຣາມ")], default="g", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="coffeereview",
            name="coffee_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="coffee.coffeeproduct",
            ),
        ),
        migrations.AlterField(
            model_name="coffeereview",
            name="reviewer_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="roastlevel",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="roastlevel",
            name="name",
            field=models.CharField(
                choices=[
                    ("light", "ຄົ່ວອ່ອນ"),
                    ("medium_light", "ຄົ່ວອ່ອນກາງ"),
                    ("medium", "ຄົ່ວກາງ"),
                    ("medium_dark", "ຄົ່ວເຂັ້ມກາງ"),
                    ("dark", "ຄົ່ວເຂັ້ມ"),
                    ("french", "ຄົ່ວແບບຝຣັ່ງ"),
                    ("italian", "ຄົ່ວແບບອິຕາລີ"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="roastlevel",
            name="temperature_range",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
