# Generated by Django 5.2 on 2025-06-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0002_alter_coffeebean_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeproduct",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="coffee_images/"),
        ),
    ]
