# Generated by Django 5.2 on 2025-06-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0004_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeproduct",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
