# Generated by Django 5.2 on 2025-06-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0005_alter_coffeeproduct_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeproduct",
            name="images",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
