# Generated by Django 5.2 on 2025-06-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0006_alter_coffeeproduct_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeecategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
