# Generated by Django 5.2 on 2025-06-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0007_coffeecategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeproduct",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
