# Generated by Django 5.2 on 2025-06-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0008_coffeeproduct_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeproduct",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
