# Generated by Django 5.2 on 2025-06-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0009_alter_coffeeproduct_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coffeeproduct",
            name="slug",
        ),
    ]
