# Generated by Django 5.2 on 2025-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_coffeeproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproduct',
            name='grind_type',
            field=models.CharField(choices=[('whole', 'Whole'), ('ground', 'Ground')], default='Whole', max_length=20),
        ),
        migrations.AlterField(
            model_name='roastlevel',
            name='name',
            field=models.CharField(choices=[('medium', 'Medium'), ('dark', 'Dark')], max_length=20, unique=True),
        ),
    ]
