# Generated by Django 5.2 on 2025-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_alter_coffeeproduct_grind_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roastlevel',
            name='name',
            field=models.CharField(choices=[('medium', 'ຄົ່ວກາງ'), ('dark', 'ຄົ່ວເຂັ້ມ'), ('medium', 'Medium'), ('dark', 'Dark')], max_length=20, unique=True),
        ),
    ]
