# Generated by Django 5.2 on 2025-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_alter_roastlevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roastlevel',
            name='name',
            field=models.CharField(choices=[('medium', 'Medium'), ('dark', 'Dark')], max_length=20, unique=True),
        ),
    ]
