# Generated by Django 5.2 on 2025-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_alter_roastlevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproduct',
            name='grind_type',
            field=models.CharField(choices=[('whole', 'Whole'), ('ground', 'Ground')], max_length=20),
        ),
    ]
