# Generated by Django 5.2 on 2025-10-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0016_alter_coffeeproduct_grind_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproduct',
            name='embed_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)', max_length=500),
        ),
    ]
