# Generated by Django 5.2 on 2025-10-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0017_coffeeproduct_embed_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeproduct',
            name='embed_video_url',
        ),
        migrations.AddField(
            model_name='coffeeproduct',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a small video file (MP4, WebM, OGV)', null=True, upload_to='products/videos/'),
        ),
    ]
